load("@bazel_skylib//:bzl_library.bzl", "bzl_library")
load("@rules_shell//shell:sh_test.bzl", "sh_test")

package(default_visibility = ["//visibility:public"])

exports_files([
    "platforms.bzl",
    "stage_cleanup.sh",
    "tectonic_pdf.bzl",
    "tectonic_repository.bzl",
    "tectonic_toolchain.bzl",
])

bzl_library(
    name = "platforms_bzl",
    srcs = ["platforms.bzl"],
)

bzl_library(
    name = "tectonic_pdf_bzl",
    srcs = ["tectonic_pdf.bzl"],
)

bzl_library(
    name = "tectonic_repository_bzl",
    srcs = ["tectonic_repository.bzl"],
    deps = [":platforms_bzl"],
)

bzl_library(
    name = "tectonic_toolchain_bzl",
    srcs = ["tectonic_toolchain.bzl"],
)

filegroup(
    name = "stage_cleanup_lib",
    srcs = ["stage_cleanup.sh"],
    visibility = ["//visibility:private"],
)

sh_test(
    name = "stage_cleanup_test",
    srcs = ["stage_cleanup_test.sh"],
    data = [":stage_cleanup_lib"],
)
