load("@rules_tectonic//tectonic:defs.bzl", "tectonic_pdf")
load(":output_files_test.bzl", "output_files_test")

tectonic_pdf(
    name = "hello",
    src = "hello.tex",
    reruns = 0,
    synctex = True,
    untrusted = True,
)

filegroup(
    name = "hello_log",
    srcs = [":hello"],
    output_group = "logs",
)

filegroup(
    name = "hello_synctex",
    srcs = [":hello"],
    output_group = "synctex",
)

output_files_test(
    name = "hello_outputs_test",
    data = [
        ":hello",
        ":hello_log",
        ":hello_synctex",
    ],
    expected_files = [
        "hello.pdf",
        "hello.log",
        "hello.synctex.gz",
    ],
)
